### PR TITLE
V2 - Functional style support

### PR DESCRIPTION
**Pull request by tisztamo**
Added some basic docs too.

There are tests in the ActorIntefacesTests.jl repo (https://github.com/JuliaActors/ActorInterfacesTests.jl/blob/main/src/suite/functional_style.jl), they run with the QuickActors.jl tests. (on the main branch both)

@pbayer please check if the tests I created are testing what you need! Feel free to also add tests to the suite!

### CODE REVIEW

**Comment by tisztamo** [comment]
Note: I did not tried but I think the ctx macro should be updated to also handle functions. (I have changed it for functors. It had an issue after your change, though: you returned expr.args instead of expr, which I reverted.)

**Comment by pbayer** [comment]
> It had an issue after your change, though: you returned expr.args

Sorry, somehow I forgot to change it back (after testing). Will look at it in the next days.

**Comment by tisztamo** [comment]
Without tests things can happen...

(I am not a fan of unit tests, but the new test suite should cover it)

**Review by pbayer — APPROVED** [review]
as far as I can see, everything is fine:

- ctx is a keyword argument and
- variable msg arguments are allowed 

thank you very much. I will next try to integrate that in `Actors`.

**Comment by pbayer** [comment]
Sorry for the delay. I couldn't work on `Actors` for some time and then what I first did took way longer than expected.

> check if the tests I created are testing what you need! Feel free to also add tests to the suite!

I added only one empty message `()` to the functional test suite and changed the `Val` stuff to structs, which is more elegant as you pointed out to me in December. 😉 (committed with [0edf44b](https://github.com/JuliaActors/ActorInterfacesTests.jl/commit/0edf44b8a6e99f2707e908d430e3c622bc5101b0))

Tests were successful with my changes to `ActorInterfacesTests`, `ActorInterfaces` V2 and `QuickActors`.

**Comment by tisztamo** [comment]
Great to see you back!

**Pull request merged**
