### PR TITLE
send, spawn, become with multiple arguments

### PR DESCRIPTION
**Pull request by pbayer**
Allow multiple arguments to `spawn`, `become` and `send` to 

- be able to give acquaintance arguments to behaviors and to
- be able to `send` multiple communication arguments

as in Agha, p. 30 and examples p. 47f, 53, 55

### CODE REVIEW

**Comment by pbayer** [comment]
The case for allowing multiple arguments to `spawn`, `become` and `send` can be made with several reasons:

1. Many behaviors have multiple arguments (particularly if one allows actors to have mathematical functions as behaviors, which I do).
2. those arguments are partitioned between acquaintance and communication arguments to behaviors (Agha on p. 30 speaks of acquaintance and communication **lists** !)
3. the need to work with multiple arguments comes quite naturally in working with actors. There are multiple examples for that (in Agha, Erlang/Elixir, Humus ... but also in `Actors`).
4. If you partition arguments to arbitrary behavior functions between acquaintances and communication, in Julia you do partial function application like that: 
`partial(f, a...; kw...) = (c...) -> f(a..., c...; kw...)`
Therefore `spawn` and `become` should allow the `f, a...` arguments and `send` the `c...` arguments.

What then to do with the `ctx` argument? I propose to make it a mandatory keyword argument for all primitives in `Classic` and I changed the `@ctx` macro to inject `ctx` as a keyword argument.

**BTW** with the PR's proposal you can still use `spawn`, `become` and `send` with single arguments only. But it gives me and our users the freedom to use multiple arguments in functions and messages as they are used to in Julia.

**Comment by tisztamo** [comment]
Thanks for this, it is now a bit more clear what you want to achieve!

In case of `spawn` and `become` I still have problems understanding the semantics of the extra arguments, because it seems that your proposal only works when `onmessage` also gets eliminated in favor of the direct call, but you did not eliminate it. So I am not sure I understand what you want.

Support for aquintances is already in the spec, the behavior itself contains them, just like the partially applied function in your example. So currently the user can/should do the partial application before spawning manually, and give the result to `spawn`/`become`. But in the current specs this is not in the form of a closure/functor but it can be any type with `onmessage` method(s) defined on it. We can change that also, but you did not.

So if I understand correctly, what you propose is this:

- Instead of `onmessage` the behavior will be called directly, so it must be callable.
- If multiple arguments are given to `spawn`/`become`, then we automatically do the partial application (functional style).
- For clarity, let's call the result of this application `stateful_behavior` for now.
- If a single argument is given to `spawn`/`become` then we use it directly as `stateful_behavior`, just like currently (oop style). (It is partial evaluation with no arguments, but the docs should be clear about what is happening, and a corner case of partial function application is not clear, especially not for OOP programmers :) ).
- The message passed to `send` can be in the form of either a single or multiple arguments.
- The message will be delivered by calling `stateful_behavior` with the message (single or multiple arguments).

Is that right?

If yes, then I would like to add the following:

- If a single argument is given to `send`, then it cannot be a tuple. (I think it helps being compatible without losing performance. I will do experiments and remove this if it seems unnecessary)

**Comment by pbayer** [comment]
Even if `onmessage` is not an element of the classical Actor model, it is justified and important to keep it since it gives us a lot of flexibility to extend the Actor model beyond classical use and - as we are talking about an interface library - it is a glue function between different implementations.

I think there is a variety of situations that must be handled by an actor via dispatching `onmessage`. I will give you some of them (the following list is inconclusive but as for now I have encountered all of them, and all of them make sense in their own right). But first let's remember how `onmessage` is defined:
```
onmessage(me, msg)
```
The variety comes from what is `me` and what is `msg` and their combinations:

- `me` is an actor variable containing a behavior (but maybe other stuff like mode, state, context, init functions ...),
- `me` is a behavior, may be a
   - _non callable object_ (with included acquaintances) with a known type,
   - _parameterless callable object_ (a function or functor, the latter with included acquaintances),
   - callable object (function or functor) with _partial arguments_,
   - a callable object (function or functor) with _full arguments_,
- `msg` is a
   - _empty argument_ to a behavior (in case we call a parameteterless callable object or a callable object which has already its full arguments),
   - _tuple of arguments_ to be passed as communication parameters to a callable object which may have already acquaintance parameters,
   - _special argument or message_ to be handled by the actor as a messaging pattern but not passed directly to the behavior. (This is a special problem solved by having `send(addr, msg::Msg)` in my case).

If you are overwhelmed by this variety, no worry! Everything can be handled by smartly dispatching `onmessage`. The key is to provide some `onmessage` _standard methods_ in an actor library: 

1. checking for special messages and eventually dispatching on them (the messaging protocol if you have one) then  
2. if it is not a special message or if you don't support those, you dispatch on the behavior object:
    - if then there is a user provided `onmessage` method for that, this is called,
    - if not, then you have as a default `onmessage(bhv, msg) = bhv(msg...)` [1].

## Conclusion

Since an actor doesn't know the communication parameters its behavior needs and which message will  arrive, it is necessary 

1. to keep `onmessage` (with at least one standard method) to have the flexibility to handle all  cases,
2. to be able to give `args...` to `bhv` in `spawn(bhv, args...)` and `become(bhv, args...)`,
3. it is convenient to have `send(addr, msg...)` | `msg... `can be empty, a single argument or multiple arguments.

**BTW** if you want to have examples for all of this, please look at the manual and the examples in the `Actors` [documentation](https://juliaactors.github.io/Actors.jl/stable/).

[1]: Maybe for working with non callable objects with one single message argument as in your case it would be better to dispatch `onmessage(bhv, msg...)`. I am not yet sure. I'd have to try.

—---

Sorry for this being a somehow complicated post. I did my best to explain. So please take time to digest it. 😅

**Comment by tisztamo** [comment]
What you describe here seems like implementation details to me, which the end user writing their program against Classic does not need to know about. Maybe every library implementing Classic will have something like this under the hood, but Classic is a programming interface, so only functions that end users will directly use should be included.

It may seem harmless to have two different ways for the user to define the behavior, the lower level `onmessage` and the higher level functor/function, but as soon as we publish a function (onmessage) to the user, we as library developers loose our freedom to change our implementations regarding it. We have to specify exactly how it works and every library must always behave the same, even if e.g. the user defines new methods of it to introduce their own protocol. That is a lot of work. We can do it later, of course, but I think it should not be in Classic, which is the minimalistic core of ActorInterfaces.

Also, the intro of Actors.jl describes a lot of interesting features that are built on top of the underlying Classic-like interface, including several protocols, but `onmessage` is not mentioned. The user does not need it to do useful work.

Of course, `onmessage` can go to an extension of Classic if we want to allow such low level work, but designing it is a much larger amount of work which I think should be done later.

**Comment by pbayer** [comment]
I can adopt your view. It makes sense from a user perspective.

In fact I was describing why I (!) need something like `onmessage`. But a user can live without it. If a user wants to use it, he can extend the method of an implementation library.

But points 2 and 3 from the conclusion above make still sense to me.

**Comment by tisztamo** [comment]
Yes, I think the new concept is clear now!

**Comment by tisztamo** [comment]
I will do the remaining changes and add basic docs if you are ok with that. (I also plan to create a test suite that libs can import and run during their tests to prove compatibility)

**Comment by tisztamo** [comment]
Replaced by #5

**Pull request closed without merging**
